# Generated by Django 3.1.6 on 2021-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_model', models.CharField(max_length=30, verbose_name='적용 프린터')),
                ('toner_name', models.CharField(max_length=30, verbose_name='토너명')),
                ('quantity', models.IntegerField(verbose_name='현재수량')),
                ('etc', models.TextField(verbose_name='비고')),
            ],
        ),
    ]
