# Generated by Django 3.1.6 on 2021-02-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': '프린터 재고관리', 'verbose_name_plural': '프린터 재고관리'},
        ),
        migrations.AlterModelTable(
            name='printer',
            table='Ptinter management',
        ),
    ]
