# Generated by Django 3.1.6 on 2021-02-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_mn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_index', models.SmallIntegerField(choices=[(0, 'input'), (1, 'output')], verbose_name='입출고여부 정하기')),
                ('reg_desc', models.TextField(verbose_name='입출고현황')),
                ('reg_qty', models.IntegerField(verbose_name='입출고수량')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='입출고일자')),
            ],
        ),
        migrations.CreateModel(
            name='TS_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_nm', models.CharField(max_length=20, verbose_name='부서')),
                ('ts_nm', models.CharField(max_length=20, verbose_name='사용자명')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer', verbose_name='프린터id')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_mn.stock_mn', verbose_name='입출고id')),
            ],
        ),
        migrations.AddField(
            model_name='stock_mn',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_mn.ts_user', verbose_name='부서'),
        ),
    ]
