# Generated by Django 3.1.6 on 2021-02-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printer', '0002_auto_20210212_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_mn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '입출고 관리',
                'verbose_name_plural': '입출고 관리',
                'db_table': 'Stock management',
            },
        ),
        migrations.CreateModel(
            name='TS_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_nm', models.CharField(max_length=20, verbose_name='부서')),
                ('ts_nm', models.CharField(max_length=20, verbose_name='사용자명')),
            ],
            options={
                'verbose_name': '현업 사용자 리스트',
                'verbose_name_plural': '현업 사용자 리스트',
                'db_table': 'TS_User',
            },
        ),
        migrations.CreateModel(
            name='Stock_printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_index', models.SmallIntegerField(choices=[(0, 'input'), (1, 'output')], default=0, verbose_name='입출고여부 정하기')),
                ('reg_desc', models.TextField(default='', verbose_name='입출고현황')),
                ('reg_qty', models.IntegerField(default=0, verbose_name='입출고수량')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='입출고일자')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer', verbose_name='프린터 코드')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_mn.stock_mn', verbose_name='입출고 부서')),
            ],
        ),
        migrations.AddField(
            model_name='stock_mn',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_mn.ts_user', verbose_name='부서'),
        ),
    ]
